import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:mergelio/domain/git/hooks.dart';

String _event(Map<String, Object?> e) => jsonEncode(e);

void main() {
  group('classifyHooks', () {
    test('executable hook is active, plain file is disabled', () {
      final hooks = classifyHooks(const [
        HookDirEntry('pre-commit', 0x1ed), // 0755
        HookDirEntry('commit-msg', 0x1a4), // 0644
      ], windows: false);
      expect(
        {for (final h in hooks) h.name: h.state},
        {'commit-msg': HookState.disabled, 'pre-commit': HookState.active},
      );
    });

    test('any execute bit counts, as it does for git', () {
      final hooks = classifyHooks(const [
        HookDirEntry('pre-push', 0x1a5), // 0645
      ], windows: false);
      expect(hooks.single.state, HookState.active);
    });

    test('a symlinked hook is marked as linked', () {
      final hooks = classifyHooks(const [
        HookDirEntry('pre-commit', 0x1ed, isLink: true),
        HookDirEntry('commit-msg', 0x1ed),
      ], windows: false);
      final linked = {for (final h in hooks) h.name: h.isLink};
      expect(linked, {'pre-commit': true, 'commit-msg': false});
    });

    test('a sample alone is listed as a sample', () {
      final hooks = classifyHooks(const [
        HookDirEntry('pre-rebase.sample', 0x1ed),
      ], windows: false);
      expect(hooks.single.name, 'pre-rebase');
      expect(hooks.single.state, HookState.sample);
    });

    test('an installed hook hides its sample', () {
      final hooks = classifyHooks(const [
        HookDirEntry('pre-commit.sample', 0x1ed),
        HookDirEntry('pre-commit', 0x1ed),
      ], windows: false);
      expect(hooks, hasLength(1));
      expect(hooks.single.state, HookState.active);
    });

    test('unknown names and helper files are ignored', () {
      final hooks = classifyHooks(const [
        HookDirEntry('h', 0x1ed),
        HookDirEntry('husky.sh', 0x1ed),
        HookDirEntry('not-a-hook.sample', 0x1ed),
      ], windows: false);
      expect(hooks, isEmpty);
    });

    test('on Windows the execute bit is not consulted', () {
      final hooks = classifyHooks(const [
        HookDirEntry('pre-commit', 0x1a4),
      ], windows: true);
      expect(hooks.single.state, HookState.active);
    });

    test('installed hooks come first, then by name', () {
      final hooks = classifyHooks(const [
        HookDirEntry('update.sample', 0x1ed),
        HookDirEntry('pre-push', 0x1a4),
        HookDirEntry('pre-commit', 0x1ed),
        HookDirEntry('commit-msg', 0x1ed),
      ], windows: false);
      expect(hooks.map((h) => h.name), [
        'commit-msg',
        'pre-commit',
        'pre-push',
        'update',
      ]);
    });
  });

  group('detectHookManager', () {
    test('husky by core.hooksPath', () {
      expect(
        detectHookManager(hooksPath: '.husky/_', hookTexts: const []),
        HookManager.husky,
      );
      expect(
        detectHookManager(hooksPath: '.husky', hookTexts: const []),
        HookManager.husky,
      );
    });

    test('lefthook and pre-commit by hook text', () {
      expect(
        detectHookManager(
          hookTexts: const ['#!/bin/sh\ncall_lefthook run "pre-commit"'],
        ),
        HookManager.lefthook,
      );
      expect(
        detectHookManager(
          hookTexts: const [
            '#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com',
          ],
        ),
        HookManager.preCommit,
      );
    });

    test('husky by the scripts its hooks source', () {
      expect(
        detectHookManager(
          hookTexts: const ['#!/bin/sh\n. "\$(dirname "\$0")/_/husky.sh"\n'],
        ),
        HookManager.husky,
      );
    });

    test('a passing mention of a tool is not an install', () {
      for (final text in [
        '#!/bin/sh\n# we moved off husky last year\nflutter analyze',
        '#!/bin/sh\n# TODO: try lefthook\nexit 0',
        '#!/bin/sh\n# see https://pre-commit.com for ideas\nexit 0',
      ]) {
        expect(detectHookManager(hookTexts: [text]), isNull, reason: text);
      }
    });

    test('plain hooks have no manager', () {
      expect(
        detectHookManager(
          hooksPath: '.githooks',
          hookTexts: const ['#!/bin/sh\nflutter analyze'],
        ),
        isNull,
      );
    });
  });

  group('rejectingHook', () {
    const sid = '20261005T1.1Z-H1-P1';

    test('a top-level session that inherited a parent sid still counts', () {
      // Launched from inside another git process, the command's own sid
      // carries that parent's as a prefix.
      const own = 'outer/$sid';
      final trace = [
        _event({'event': 'version', 'sid': own}),
        _event({
          'event': 'child_start',
          'sid': own,
          'child_id': 0,
          'child_class': 'hook',
          'hook_name': 'pre-commit',
        }),
        _event({'event': 'child_exit', 'sid': own, 'child_id': 0, 'code': 1}),
      ].join('\n');
      expect(rejectingHook(trace), 'pre-commit');
    });

    test('names the hook that exited non-zero', () {
      final trace = [
        _event({'event': 'version', 'sid': sid}),
        _event({
          'event': 'child_start',
          'sid': sid,
          'child_id': 0,
          'child_class': 'hook',
          'hook_name': 'pre-commit',
          'argv': ['.git/hooks/pre-commit'],
        }),
        _event({'event': 'child_exit', 'sid': sid, 'child_id': 0, 'code': 1}),
      ].join('\n');
      expect(rejectingHook(trace), 'pre-commit');
    });

    test('a passing hook followed by a failing one', () {
      final trace = [
        _event({
          'event': 'child_start',
          'sid': sid,
          'child_id': 0,
          'child_class': 'hook',
          'hook_name': 'pre-commit',
        }),
        _event({'event': 'child_exit', 'sid': sid, 'child_id': 0, 'code': 0}),
        _event({
          'event': 'child_start',
          'sid': sid,
          'child_id': 1,
          'child_class': 'hook',
          'hook_name': 'commit-msg',
        }),
        _event({'event': 'child_exit', 'sid': sid, 'child_id': 1, 'code': 1}),
      ].join('\n');
      expect(rejectingHook(trace), 'commit-msg');
    });

    test('nested git sessions started by the hook are ignored', () {
      final trace = [
        _event({
          'event': 'child_start',
          'sid': sid,
          'child_id': 0,
          'child_class': 'hook',
          'hook_name': 'pre-commit',
        }),
        // The hook ran `git commit` itself, whose own hook failed.
        _event({
          'event': 'child_start',
          'sid': '$sid/nested',
          'child_id': 0,
          'child_class': 'hook',
          'hook_name': 'commit-msg',
        }),
        _event({
          'event': 'child_exit',
          'sid': '$sid/nested',
          'child_id': 0,
          'code': 1,
        }),
        _event({'event': 'child_exit', 'sid': sid, 'child_id': 0, 'code': 0}),
      ].join('\n');
      expect(rejectingHook(trace), isNull);
    });

    test('a hook in the git commit the command spawned counts', () {
      // cherry-pick --continue commits through a child `git commit`, so its
      // hooks run one session down.
      final trace = [
        _event({
          'event': 'child_start',
          'sid': sid,
          'child_id': 0,
          'child_class': '?',
          'argv': ['git', 'commit', '--no-edit'],
        }),
        _event({
          'event': 'child_start',
          'sid': '$sid/c1',
          'child_id': 0,
          'child_class': 'hook',
          'hook_name': 'pre-commit',
        }),
        _event({
          'event': 'child_exit',
          'sid': '$sid/c1',
          'child_id': 0,
          'code': 1,
        }),
        _event({'event': 'child_exit', 'sid': sid, 'child_id': 0, 'code': 1}),
      ].join('\n');
      expect(rejectingHook(trace), 'pre-commit');
    });

    test('only the next session down is followed', () {
      final trace = [
        _event({
          'event': 'child_start',
          'sid': sid,
          'child_id': 0,
          'child_class': '?',
        }),
        _event({
          'event': 'child_start',
          'sid': '$sid/c1/c2',
          'child_id': 0,
          'child_class': 'hook',
          'hook_name': 'pre-commit',
        }),
        _event({
          'event': 'child_exit',
          'sid': '$sid/c1/c2',
          'child_id': 0,
          'code': 1,
        }),
      ].join('\n');
      expect(rejectingHook(trace), isNull);
    });

    test('a start event is never read as an exit', () {
      final trace = [
        _event({
          'event': 'child_start',
          'sid': sid,
          'child_id': 0,
          'child_class': 'hook',
          'hook_name': 'pre-commit',
        }),
        // A hypothetical start that carries a code must not end the hook.
        _event({
          'event': 'child_start',
          'sid': sid,
          'child_id': 0,
          'child_class': 'filter',
          'code': 1,
        }),
      ].join('\n');
      expect(rejectingHook(trace), isNull);
    });

    test('falls back to argv when hook_name is absent', () {
      final trace = [
        _event({
          'event': 'child_start',
          'sid': sid,
          'child_id': 3,
          'child_class': 'hook',
          'argv': ['/repo/.git/hooks/commit-msg', '.git/COMMIT_EDITMSG'],
        }),
        _event({'event': 'child_exit', 'sid': sid, 'child_id': 3, 'code': 1}),
      ].join('\n');
      expect(rejectingHook(trace), 'commit-msg');
    });

    test('non-hook children and garbage lines do not count', () {
      final trace = [
        'not json',
        _event({
          'event': 'child_start',
          'sid': sid,
          'child_id': 0,
          'child_class': 'gpg',
        }),
        _event({'event': 'child_exit', 'sid': sid, 'child_id': 0, 'code': 1}),
      ].join('\n');
      expect(rejectingHook(trace), isNull);
    });
  });

  group('hookFilePath', () {
    test('joins a known hook name onto the directory', () {
      expect(
        hookFilePath('/r/.git/hooks', 'pre-commit'),
        '/r/.git/hooks/pre-commit',
      );
    });

    test('refuses anything that is not a hook name', () {
      for (final bad in ['../config', 'pre-commit/../x', 'h', '', '.']) {
        expect(() => hookFilePath('/r/.git/hooks', bad), throwsArgumentError);
      }
    });
  });

  test('only the hooks --no-verify really skips are offered as skippable', () {
    expect(noVerifyHooks, {'pre-commit', 'commit-msg', 'pre-merge-commit'});
  });
}
