#!/usr/bin/env bash
#
# build-macos-dmg.sh — build, sign, package and notarize the macOS app.
#
# Configuration is read from .env in the repository root (see .env.example).
# Variables already set in the environment take precedence over .env.
#
# Usage:
#   ./scripts/build-macos-dmg.sh                  # version taken from pubspec.yaml
#   ./scripts/build-macos-dmg.sh 1.4.2            # explicit version in the DMG name
#   CLEAN=1 ./scripts/build-macos-dmg.sh          # flutter clean before building
#   SKIP_GEN=1 ./scripts/build-macos-dmg.sh       # skip code generation
#   SKIP_NOTARIZE=1 ./scripts/build-macos-dmg.sh  # stop right after signing the .app
#
# Without MACOS_SIGN_IDENTITY the script builds an ad-hoc signed .app for local
# use and stops there — no Apple certificate required.

set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
enter_repo_root

# ─── Configuration ───────────────────────────────────────────────────────────

load_env .env

APP_NAME=${APP_NAME:-Mergelio}
DIST_DIR=${DIST_DIR:-dist}
ENTITLEMENTS=${MACOS_ENTITLEMENTS:-macos/Runner/Release.entitlements}
SIGN_IDENTITY=${MACOS_SIGN_IDENTITY:-}
TEAM_ID=${MACOS_TEAM_ID:-}
NOTARY_PROFILE=${MACOS_NOTARY_PROFILE:-}
SIGNING_XCCONFIG=macos/Runner/Configs/Signing.xcconfig

# The Team ID is usually already part of the certificate name: "... (ABCDE12345)".
if [[ -z $TEAM_ID && $SIGN_IDENTITY =~ \(([A-Z0-9]{10})\)[[:space:]]*$ ]]; then
  TEAM_ID=${BASH_REMATCH[1]}
fi

SIGNED=0
[[ -n $SIGN_IDENTITY ]] && SIGNED=1

NOTARIZE=0
if (( SIGNED )) && [[ -z ${SKIP_NOTARIZE:-} && -n $NOTARY_PROFILE ]]; then
  NOTARIZE=1
fi

# ─── 0. Preflight checks ─────────────────────────────────────────────────────

step "Checking environment"

[[ -f pubspec.yaml && -d macos ]] || die "Run this from the repository root."
command -v flutter >/dev/null 2>&1 || die "flutter not found in PATH."
ok "Repository root and flutter are in place"

if (( SIGNED )); then
  [[ -f $ENTITLEMENTS ]] || die "Entitlements file missing: $ENTITLEMENTS"

  if grep -q "get-task-allow" "$ENTITLEMENTS"; then
    die "$ENTITLEMENTS contains get-task-allow — remove it before releasing."
  fi

  security find-identity -v -p codesigning 2>/dev/null | grep -qF "$SIGN_IDENTITY" \
    || die "Certificate not found in the keychain:\n  $SIGN_IDENTITY"

  [[ -n $TEAM_ID ]] \
    || die "Set MACOS_TEAM_ID in .env — it could not be derived from the certificate name."

  ok "Certificate: $SIGN_IDENTITY"
  ok "Team ID: $TEAM_ID"

  if [[ -z ${SKIP_NOTARIZE:-} ]]; then
    command -v create-dmg >/dev/null 2>&1 \
      || die "'create-dmg' missing. Install it with: brew install create-dmg"
  fi
else
  warn "MACOS_SIGN_IDENTITY is empty — the build will be ad-hoc signed."
  warn "That is fine for local use. For distribution, fill in .env"
  warn "using .env.example as the template."
fi

if (( NOTARIZE )); then
  xcrun notarytool history --keychain-profile "$NOTARY_PROFILE" >/dev/null 2>&1 \
    || die "Notary profile '$NOTARY_PROFILE' is not available.\n  Create it with: xcrun notarytool store-credentials"
  ok "Notary profile: $NOTARY_PROFILE"
elif (( SIGNED )) && [[ -z ${SKIP_NOTARIZE:-} ]]; then
  warn "MACOS_NOTARY_PROFILE is empty — the DMG will be signed but not notarized."
fi

# ─── 1. Version ──────────────────────────────────────────────────────────────

if (( $# >= 1 )); then
  VERSION=$1
else
  VERSION=$(grep -m1 '^version:' pubspec.yaml | sed -E 's/^version:[[:space:]]*//; s/\+.*$//')
fi

[[ -n $VERSION ]] || die "Could not determine the version."

# Named like every other artifact, so the release assets sort together.
case "$(uname -m)" in
  arm64|aarch64) ARCH=arm64 ;;
  *)             ARCH=x64   ;;
esac

DMG_PATH="${DIST_DIR}/${APP_NAME}-${VERSION}-macos-${ARCH}.dmg"
ok "Version: $VERSION"

# ─── 2. Signing configuration for Xcode ──────────────────────────────────────
# AppInfo.xcconfig includes this file optionally, so its absence in a fresh
# clone breaks nothing — the ad-hoc values from SigningDefaults.xcconfig apply.

step "Writing signing configuration for Xcode"

mkdir -p "$(dirname "$SIGNING_XCCONFIG")"
{
  printf '// Generated by scripts/build-macos-dmg.sh from .env. Do not commit.\n'
  if (( SIGNED )); then
    printf 'MERGELIO_CODE_SIGN_IDENTITY = Developer ID Application\n'
    printf 'MERGELIO_TEAM_ID = %s\n' "$TEAM_ID"
  else
    printf 'MERGELIO_CODE_SIGN_IDENTITY = -\n'
    printf 'MERGELIO_TEAM_ID =\n'
  fi
} > "$SIGNING_XCCONFIG"

ok "Wrote $SIGNING_XCCONFIG"

# ─── 3. Build ────────────────────────────────────────────────────────────────

maybe_clean
prepare_sources

step "Building (flutter build macos --release)"

flutter build macos --release

PRODUCTS_DIR="build/macos/Build/Products/Release"

# Take the name off disk rather than assuming "$APP_NAME.app": PRODUCT_NAME is
# lowercase, and on a case-insensitive volume a guessed name would silently
# match while a case-sensitive one would not.
APP_PATH=$(find "$PRODUCTS_DIR" -maxdepth 1 -name '*.app' -print -quit 2>/dev/null || true)

[[ -n $APP_PATH && -d $APP_PATH ]] || die "No app was produced in $PRODUCTS_DIR"
ok "Built: $APP_PATH"

if (( ! SIGNED )); then
  printf '\n%s✓ Done: %s%s\n' "$GREEN" "$APP_PATH" "$OFF"
  printf '  The build is ad-hoc signed — fine to run locally.\n\n'
  exit 0
fi

# ─── 4. Re-sign ──────────────────────────────────────────────────────────────
# Two things are wrong with what Xcode leaves behind. It injects
# com.apple.security.get-task-allow even in Release builds, and not every
# nested framework carries a secure timestamp — the notary service rejects the
# whole archive over a single one that does not.
#
# Signing runs inside out: nested code first, the bundle last, because signing
# the outer bundle seals whatever the inner signatures are at that moment.
# Still NOT --deep, which Apple discourages: it would apply the app's
# entitlements to every framework as well.

step "Re-signing nested code"

rm -f "${APP_PATH}/Contents/embedded.provisionprofile"

nested=0
while IFS= read -r -d '' item; do
  # Versioned frameworks are signed at Versions/A; codesign rejects the
  # .framework wrapper for those.
  target=$item
  [[ -d "$item/Versions/A" ]] && target="$item/Versions/A"

  codesign --force \
    --sign "$SIGN_IDENTITY" \
    --options runtime \
    --timestamp \
    "$target"
  nested=$((nested + 1))
done < <(find "${APP_PATH}/Contents" -depth \
  \( -name '*.framework' -o -name '*.dylib' -o -name '*.bundle' \) -print0)

ok "Re-signed $nested nested items"

step "Re-signing with clean entitlements"

codesign --force \
  --sign "$SIGN_IDENTITY" \
  --options runtime \
  --timestamp \
  --entitlements "$ENTITLEMENTS" \
  "$APP_PATH"

ok "Signed"

# ─── 5. Signature validation ─────────────────────────────────────────────────

step "Validating the signature"

SIGN_INFO=$(codesign -dvv "$APP_PATH" 2>&1)

grep -q "Authority=Developer ID Application" <<<"$SIGN_INFO" \
  || die "Signature is not Developer ID Application:\n$(grep 'Authority=' <<<"$SIGN_INFO" | head -1)"
ok "Authority: Developer ID Application"

grep -q "flags=.*runtime" <<<"$SIGN_INFO" \
  || die "Hardened runtime is not enabled."
ok "Hardened runtime enabled"

grep -q "^Timestamp=" <<<"$SIGN_INFO" \
  || die "Secure timestamp is missing."
ok "Secure timestamp present"

if codesign -d --entitlements - "$APP_PATH" 2>&1 | grep -q "get-task-allow"; then
  die "get-task-allow is still present in the signed bundle."
fi
ok "No get-task-allow"

codesign --verify --deep --strict "$APP_PATH" 2>/dev/null \
  || die "codesign --verify failed."
ok "codesign --verify passed"

if [[ -n ${SKIP_NOTARIZE:-} ]]; then
  printf '\n%s✓ SKIP_NOTARIZE=1 — stopping after signing: %s%s\n\n' "$GREEN" "$APP_PATH" "$OFF"
  exit 0
fi

# ─── 6. DMG ──────────────────────────────────────────────────────────────────

step "Packaging the DMG"

mkdir -p "$DIST_DIR"
rm -f "$DMG_PATH"

create-dmg \
  --volname "$APP_NAME" \
  --window-size 600 400 \
  --icon-size 100 \
  --icon "$(basename "$APP_PATH")" 150 200 \
  --app-drop-link 450 200 \
  --no-internet-enable \
  "$DMG_PATH" \
  "$APP_PATH" \
  || [[ -f $DMG_PATH ]] || die "create-dmg did not produce an image."

codesign --sign "$SIGN_IDENTITY" --timestamp "$DMG_PATH"
ok "DMG created and signed: $DMG_PATH"

if (( ! NOTARIZE )); then
  printf '\n%s✓ Done (not notarized): %s%s\n\n' "$GREEN" "$DMG_PATH" "$OFF"
  exit 0
fi

# ─── 7. Notarization ─────────────────────────────────────────────────────────

step "Notarizing (usually 1–5 minutes)"

NOTARY_LOG=$(mktemp -t notary)
trap 'rm -f "$NOTARY_LOG"' EXIT

set +e
xcrun notarytool submit "$DMG_PATH" \
  --keychain-profile "$NOTARY_PROFILE" \
  --wait 2>&1 | tee "$NOTARY_LOG"
set -e

SUBMISSION_ID=$(grep -m1 -E '^[[:space:]]*id:' "$NOTARY_LOG" | awk '{print $2}' || true)
STATUS=$(grep -m1 -E '^[[:space:]]*status:' "$NOTARY_LOG" | awk '{print $2}' || true)

if [[ $STATUS != "Accepted" ]]; then
  printf '\n%s─── Rejection details ───%s\n' "$YELLOW" "$OFF"
  [[ -n $SUBMISSION_ID ]] && \
    xcrun notarytool log "$SUBMISSION_ID" --keychain-profile "$NOTARY_PROFILE" || true
  die "Notarization failed (status: ${STATUS:-unknown})."
fi

ok "Status: Accepted"

# ─── 8. Staple and final check ───────────────────────────────────────────────

step "Stapling the ticket"

xcrun stapler staple "$DMG_PATH"
xcrun stapler validate "$DMG_PATH" >/dev/null
ok "Ticket stapled"

SPCTL_OUT=$(spctl -a -vvv -t install "$DMG_PATH" 2>&1)

if grep -q "Developer ID" <<<"$SPCTL_OUT"; then
  ok "Gatekeeper: Developer ID"
else
  warn "Unexpected spctl output:"
  printf '%s\n' "$SPCTL_OUT"
fi

SIZE=$(du -h "$DMG_PATH" | cut -f1)

printf '\n%s✓ Done%s\n' "$GREEN" "$OFF"
printf '  %s (%s)\n\n' "$DMG_PATH" "$SIZE"
