import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

import '../file_edit.dart';
import 'git_service.dart';

/// Every hook git knows by name. Only these are listed, and only these may be
/// written: the name check is what keeps a write inside the hooks directory.
const gitHookNames = {
  'applypatch-msg',
  'pre-applypatch',
  'post-applypatch',
  'pre-commit',
  'pre-merge-commit',
  'prepare-commit-msg',
  'commit-msg',
  'post-commit',
  'pre-rebase',
  'post-checkout',
  'post-merge',
  'pre-push',
  'pre-receive',
  'update',
  'proc-receive',
  'post-receive',
  'post-update',
  'reference-transaction',
  'push-to-checkout',
  'pre-auto-gc',
  'post-rewrite',
  'sendemail-validate',
  'fsmonitor-watchman',
  'p4-changelist',
  'p4-prepare-changelist',
  'p4-post-changelist',
  'p4-pre-submit',
  'post-index-change',
};

/// The hooks a plain `git commit` runs that `--no-verify` skips.
const noVerifyHooks = {'pre-commit', 'commit-msg'};

const _sampleSuffix = '.sample';

/// How much of an installed hook is read to recognise the tool that wrote it.
const _markerBytes = 4096;

enum HookState {
  /// Present and git will run it.
  active,

  /// Present, but without an execute bit, so git skips it.
  disabled,

  /// Only git's `<name>.sample` template exists.
  sample,
}

/// One plain file in the hooks directory, as listed: name and POSIX mode.
class HookDirEntry {
  final String name;
  final int mode;
  const HookDirEntry(this.name, this.mode);
}

class HookFile {
  final String name;
  final HookState state;

  /// Whether git's template for this hook sits beside it.
  final bool hasSample;
  const HookFile(this.name, this.state, {this.hasSample = false});

  bool get installed => state != HookState.sample;
}

/// Sorts the hooks directory into the hooks it holds. Git skips a hook with
/// no execute bit for owner, group or other on POSIX; on Windows it runs
/// every hook regardless, so [windows] never reports one as disabled.
List<HookFile> classifyHooks(
  Iterable<HookDirEntry> entries, {
  required bool windows,
}) {
  final modes = <String, int>{};
  final samples = <String>{};
  for (final e in entries) {
    if (e.name.endsWith(_sampleSuffix)) {
      final name = e.name.substring(0, e.name.length - _sampleSuffix.length);
      if (gitHookNames.contains(name)) samples.add(name);
    } else if (gitHookNames.contains(e.name)) {
      modes[e.name] = e.mode;
    }
  }
  final hooks = [
    for (final MapEntry(key: name, value: mode) in modes.entries)
      HookFile(
        name,
        windows || mode & 0x49 != 0 ? HookState.active : HookState.disabled,
        hasSample: samples.contains(name),
      ),
    for (final name in samples)
      if (!modes.containsKey(name)) HookFile(name, HookState.sample),
  ];
  // Installed hooks first, since they are what runs; samples trail behind.
  hooks.sort((a, b) {
    if (a.installed != b.installed) return a.installed ? -1 : 1;
    return a.name.compareTo(b.name);
  });
  return hooks;
}

/// A tool that installs and regenerates the hooks itself, so edits made here
/// may be overwritten the next time it runs.
enum HookManager { husky, lefthook, preCommit }

/// Recognises the hook manager from install evidence only: where
/// `core.hooksPath` points and what the installed hooks say. A manager's
/// config file in the tree without its hooks installed is not counted.
HookManager? detectHookManager({
  String? hooksPath,
  required Iterable<String> hookTexts,
}) {
  if (hooksPath != null) {
    final parts = p.posix.split(hooksPath.replaceAll(r'\', '/'));
    if (parts.isNotEmpty &&
        (parts.last == '.husky' ||
            (parts.last == '_' &&
                parts.length > 1 &&
                parts[parts.length - 2] == '.husky'))) {
      return HookManager.husky;
    }
  }
  for (final text in hookTexts) {
    if (text.contains('lefthook')) return HookManager.lefthook;
    if (text.contains('pre-commit.com') ||
        text.contains('File generated by pre-commit')) {
      return HookManager.preCommit;
    }
    if (text.contains('husky')) return HookManager.husky;
  }
  return null;
}

/// The hook that made a git command fail, read from the `GIT_TRACE2_EVENT`
/// stream it wrote, or null when no hook exited non-zero.
///
/// Only the command's own session counts: a hook that runs git itself
/// appends that child's events to the same file under a nested session id,
/// and a failure in there is not the hook's verdict.
String? rejectingHook(String trace2Events) {
  String? session;
  final started = <Object?, String>{};
  for (final line in const LineSplitter().convert(trace2Events)) {
    final Object? decoded;
    try {
      decoded = jsonDecode(line);
    } on FormatException {
      continue;
    }
    if (decoded is! Map<String, Object?>) continue;
    final sid = decoded['sid'];
    if (sid is! String) continue;
    // The top-level session is the one without a parent prefix.
    session ??= sid.contains('/') ? null : sid;
    if (sid != session) continue;
    switch (decoded['event']) {
      case 'child_start' when decoded['child_class'] == 'hook':
        final name = decoded['hook_name'] ?? _argvHookName(decoded['argv']);
        if (name is String) started[decoded['child_id']] = name;
      case 'child_exit':
        final name = started[decoded['child_id']];
        final code = decoded['code'];
        if (name != null && code is int && code != 0) return name;
    }
  }
  return null;
}

/// Older git names a hook child only by the path it ran.
String? _argvHookName(Object? argv) {
  if (argv is! List || argv.isEmpty || argv.first is! String) return null;
  final name = p.basename((argv.first as String).replaceAll(r'\', '/'));
  return gitHookNames.contains(name) ? name : null;
}

/// A git command refused by one of the repository's hooks. The result holds
/// what the hook printed.
class HookRejectedException extends GitException {
  final String hook;
  HookRejectedException(this.hook, GitResult result)
    : super('The $hook hook rejected the commit', result);
}

/// The file for hook [name] inside [dir]. Throws [ArgumentError] for anything
/// that is not a hook git knows, which also rules out separators and `..`.
String hookFilePath(String dir, String name) {
  if (!gitHookNames.contains(name)) {
    throw ArgumentError.value(name, 'name', 'not a git hook');
  }
  return p.join(dir, name);
}

/// What the hooks manager knows about one repository.
class HookInventory {
  /// Absolute hooks directory git uses for this repository.
  final String dir;

  /// `core.hooksPath` as configured, or null when git uses the default.
  final String? customPath;
  final List<HookFile> hooks;
  final HookManager? manager;

  const HookInventory({
    required this.dir,
    this.customPath,
    this.hooks = const [],
    this.manager,
  });
}

/// Reads the hooks directory git would use for [repoPath]. `--git-path`
/// already accounts for `core.hooksPath` and for linked worktrees, which keep
/// their hooks in the main repository.
Future<HookInventory> readHookInventory(
  GitService git,
  String repoPath, {
  bool? windows,
}) async {
  final r = await git.run([
    'rev-parse',
    '--git-path',
    'hooks',
  ], repoPath: repoPath);
  if (!r.ok) throw GitException('git rev-parse --git-path hooks', r);
  final dir = p.normalize(
    p.isAbsolute(r.out) ? r.out : p.join(repoPath, r.out),
  );
  final cfg = await git.run([
    'config',
    '--get',
    'core.hooksPath',
  ], repoPath: repoPath);
  final custom = cfg.ok && cfg.out.isNotEmpty ? cfg.out : null;

  final entries = <HookDirEntry>[];
  final directory = Directory(dir);
  if (await directory.exists()) {
    await for (final e in directory.list(followLinks: false)) {
      // A symlinked hook is common (a script kept in the repo); stat follows
      // it so the mode is the one git will see.
      final stat = await FileStat.stat(e.path);
      if (stat.type != FileSystemEntityType.file) continue;
      entries.add(HookDirEntry(p.basename(e.path), stat.mode));
    }
  }
  final hooks = classifyHooks(entries, windows: windows ?? Platform.isWindows);
  final texts = <String>[];
  for (final h in hooks.where((h) => h.installed)) {
    texts.add(await _head(File(p.join(dir, h.name))));
  }
  return HookInventory(
    dir: dir,
    customPath: custom,
    hooks: hooks,
    manager: detectHookManager(hooksPath: custom, hookTexts: texts),
  );
}

Future<String> _head(File file) async {
  try {
    final bytes = await file
        .openRead(0, _markerBytes)
        .expand((chunk) => chunk)
        .toList();
    return utf8.decode(bytes, allowMalformed: true);
  } on FileSystemException {
    return '';
  }
}

/// Resolves the hook file about to be written and refuses it when its real
/// location is outside both the hooks directory and the repository — a
/// symlinked hook may point into the repo's own scripts, never elsewhere.
Future<File> _guardedHook(String dir, String name, String repoPath) async {
  final file = File(hookFilePath(dir, name));
  if (await FileSystemEntity.isLink(file.path)) {
    final real = await file.resolveSymbolicLinks();
    final realDir = await Directory(dir).resolveSymbolicLinks();
    final realRepo = await Directory(repoPath).resolveSymbolicLinks();
    if (!isWithinOrEqual(realDir, real) && !isWithinOrEqual(realRepo, real)) {
      throw FileSystemException('Hook links outside the repository', file.path);
    }
  }
  return file;
}

/// Turns hook [name] on or off by its execute bits — the switch git itself
/// reads. Only meaningful on POSIX; Windows runs hooks regardless.
Future<void> setHookEnabled(
  String dir,
  String name, {
  required bool enabled,
  required String repoPath,
}) async {
  final file = await _guardedHook(dir, name, repoPath);
  if (!await file.exists()) {
    throw FileSystemException('No such hook', file.path);
  }
  final r = await Process.run('chmod', [enabled ? '+x' : 'a-x', file.path]);
  if (r.exitCode != 0) {
    throw FileSystemException('chmod failed: ${r.stderr}'.trim(), file.path);
  }
}

/// Saves new text for an existing hook. Writing in place keeps its mode, so
/// an enabled hook stays enabled.
Future<void> writeHook(
  String dir,
  String name,
  String text, {
  required String repoPath,
}) async {
  final file = await _guardedHook(dir, name, repoPath);
  if (!await file.exists()) {
    throw FileSystemException('No such hook', file.path);
  }
  await file.writeAsString(text, flush: true);
}

/// Installs hook [name] from git's sample beside it and makes it executable.
/// Never replaces a hook that is already there.
Future<void> installSample(
  String dir,
  String name, {
  required String repoPath,
}) async {
  final file = await _guardedHook(dir, name, repoPath);
  if (await FileSystemEntity.type(file.path, followLinks: false) !=
      FileSystemEntityType.notFound) {
    throw FileSystemException('Hook already exists', file.path);
  }
  await File('${file.path}$_sampleSuffix').copy(file.path);
  if (!Platform.isWindows) {
    await setHookEnabled(dir, name, enabled: true, repoPath: repoPath);
  }
}
